<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>proyecto comunicacion</title>
	<link rel="stylesheet" href="<?=$assets_css?>bootstrap.min.css">
	<link rel="stylesheet" href="<?=$assets_css?>animate.css">
	<link rel="stylesheet" href="<?=$assets_css?>custom.css">
</head>
<body>
	<div class="page-content">